### ISSUE TITLE
Siphash seems to be broken on Python 3.11.1 

### ISSUE THREAD

**Issue by l1x** [dnicolodi/python-siphash24#2]
Maybe I am not doing something right?

```Python
>>> import siphash24
>>> siphash24.siphash13(data=b'', key=b'')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "siphash24.pyx", line 61, in siphash24.siphash13.__init__
TypeError: __init__() got an unexpected keyword argument 'data'
>>> siphash24.siphash13(b'', b'')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "siphash24.pyx", line 61, in siphash24.siphash13.__init__
TypeError: __init__() takes at most 1 positional argument (2 given)
>>> h = siphash24.siphash13(b'', b'')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "siphash24.pyx", line 61, in siphash24.siphash13.__init__
TypeError: __init__() takes at most 1 positional argument (2 given)
```

**Comment by dnicolodi** [comment]
Works as intended: the `data` parameter is a positional only argument, the second is a keyword only argument
```python
>>> import siphash24
>>> siphash24.siphash13(b'', key=b'foo')
<siphash24.siphash13 object at 0x000001D089A0F410>
```
This mimics the interface of the hash function in the `hashlib` standard library module, for example `hashlib.blake2b()` https://docs.python.org/3/library/hashlib.html#hashlib.blake2b However, I see how the signature in the `siphash24()` documentation may be misleading. I'll update it.
